name: Papandayan Project Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
      with:
        php-version: '7.4'
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: Check 'cargo.ivalpha.com' service url
      uses: jtalk/url-health-check-action@v1.2
      with:
        url: https://cargo.ivalpha.com/public/
        max-attempts: 3
        retry-delay: 5s
    - name: Deploy to 'cargo.ivalpha.com'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_IVALPHA }}
        username: ${{ secrets.SSH_USERNAME_IVALPHA }}
        password: ${{ secrets.SSH_PASSWORD_IVALPHA }}
        port: ${{ secrets.PORT_IVALPHA }}
        script: |
          cd cargo.ivalpha.com
          git checkout main
          git pull
          composer install
          exit
    # - name: Install Dependencies
    #   run: composer install
